const state={screen:'CEO',taskFilter:'ALL',taskSearch:'',tasks:[
{id:'T-001',name:'Convert CGS 80 kWp LOI into executed PPA',meta:'Commercial · CGS',tag:'P0',status:'Active',impact:'Critical',class:'SCALE',due:'Now',blocked:false},
{id:'T-002',name:'Finalize project financial model',meta:'Finance · Bankability',tag:'P0',status:'Active',impact:'Critical',class:'SCALE',due:'Now',blocked:false},
{id:'T-003',name:'Resolve IDCOL / PFI guarantee requirements',meta:'Financing · IDCOL',tag:'P0',status:'Active',impact:'Critical',class:'SCALE',due:'Now',blocked:true},
{id:'T-004',name:'Complete GuarantCo consolidated submission',meta:'Financing · GuarantCo',tag:'P0',status:'Active',impact:'High',class:'SCALE',due:'Now',blocked:false},
{id:'T-005',name:'Validate CGS technical + structural assumptions',meta:'Technical · CGS',tag:'P1',status:'Active',impact:'High',class:'SCALE',due:'Next',blocked:false},
{id:'T-006',name:'Build qualified target list of next 20–50 customers',meta:'Commercial · Pipeline',tag:'P1',status:'Active',impact:'High',class:'SCALE',due:'Next',blocked:false}
],projects:[{id:'P-001',name:'Chittagong Grammar School',size:'80 kWp',stage:'LOI',progress:38,truth:'LOI / needs execution',ppr:'BDT 10/kWh',term:'20 years',generation:'~115,632 kWh/yr',capex:'TBD'},{id:'P-002',name:'Other pipeline prospects',size:'TBD',stage:'Qualification',progress:12,truth:'Unverified',ppr:'TBD',term:'TBD',generation:'TBD',capex:'TBD'}],finance:[{name:'IDCOL / PFI',stage:'Requirements',next:'Validate financing/security structure',truth:'Needs confirmation'},{name:'GuarantCo',stage:'Submission',next:'Complete consolidated project pack',truth:'Application workstream'},{name:'Investor capital',stage:'Pipeline',next:'Finalize one-pager + deck',truth:'Fundraising workstream'}]};
const screens={CEO:['Executive operating system','CEO Command Center'],Tasks:['Execution','Tasks'],Projects:['Delivery','Projects'],Pipeline:['Commercial','Customer Pipeline'],Financing:['Capital','Financing'],Portfolio:['Assets','Portfolio'],Risks:['Governance','Risks & Decisions'],Roadmap:['Strategy','90-Day Roadmap'],Documents:['Knowledge','Documents & Knowledge']};
const nav=[['CEO','LayoutDashboard'],['Tasks','CheckSquare'],['Projects','Boxes'],['Pipeline','Users'],['Financing','Landmark'],['Portfolio','SolarPanel'],['Risks','ShieldAlert'],['Roadmap','Milestone'],['Documents','FolderOpen']];
const icon=n=>`<i data-lucide="${n}"></i>`;
function sidebar(){return `<aside class="sidebar"><div class="brand"><strong>NETSO OS</strong><span>CEO Command Center</span></div><nav class="nav">${nav.map(([n,i])=>`<button class="${state.screen===n?'active':''}" onclick="go('${n}')">${icon(i)}<span>${n}</span></button>`).join('')}</nav><div class="source-note">SOURCE OF TRUTH<br><span>V1 local data · Notion integration planned</span></div></aside>`}
function header(){const s=screens[state.screen];return `<div class="topbar"><div><div class="eyebrow">${s[0]}</div><div class="title">${s[1]}</div></div><div class="actions"><button class="btn" onclick="go('Tasks');document.getElementById('taskSearch')?.focus()">${icon('Search')} Search</button><button class="btn primary" onclick="newTask()">${icon('Plus')} New task</button></div></div>`}
function kpi(label,value,sub,kind='unknown'){return `<div class="card kpi"><div class="label">${label}</div><div class="value ${kind}">${value}</div><div class="sub">${sub}</div></div>`}
function taskRows(tasks){if(!tasks.length)return `<tr><td colspan="5"><div class="empty compact">No tasks match the current filters.</div></td></tr>`;return tasks.map(t=>`<tr><td><b>${t.name}</b><small>${t.meta}</small></td><td><span class="badge ${t.tag==='P0'?'p0':''}">${t.tag}</span></td><td>${t.impact}</td><td><span class="status">${t.blocked?'Blocked':t.status}</span></td><td><button class="btn" onclick="alert('${t.name.replace(/'/g,"\\'")}\n\nPriority: ${t.tag}\nClassification: ${t.class}\nEvidence: operational task record')">Open</button></td></tr>`).join('')}
function dashboard(){const active=state.tasks.filter(t=>t.status==='Active');return `<div class="objective"><div class="label">90-day objective · active</div><h2>MAKE NETSO FINANCEABLE AND DEPLOYABLE</h2><p>Contracts → bankability → financing → first deployment. Everything else is subordinate.</p><div class="objective-meta"><span>${icon('Target')} Contract conversion</span><span>${icon('Landmark')} Financing</span><span>${icon('Rocket')} Deployment</span></div></div><div class="grid kpis">${kpi('Executed PPAs','TBD','Target: 3')}${kpi('Contracted MW','TBD','Not yet tracked')}${kpi('Installed MW','TBD','Not yet tracked')}${kpi('Qualified Projects','TBD','Target: 20+')}${kpi('Financing Secured','TBD','First project')}${kpi('Active Financing','3','IDCOL · GuarantCo · Investors','known')}${kpi('Critical Blockers',String(state.tasks.filter(t=>t.blocked).length),'Tracked in V1','known')}</div><div class="grid cols"><section class="card"><div class="section-title"><h3>Today — Top 5</h3><span class="badge">P0 / P1</span></div>${active.slice(0,5).map(t=>`<div class="task"><span class="dot ${t.tag==='P1'?'warn':''}"></span><div class="grow"><b>${t.name}</b><small>${t.meta} · ${t.class}</small></div><span class="badge ${t.tag==='P0'?'p0':''}">${t.tag}</span></div>`).join('')}</section><section class="card"><div class="section-title"><h3>Financing snapshot</h3><span class="badge">Status tracking</span></div>${state.finance.map(f=>`<div class="funnel"><div><span>${f.name}</span><b>${f.stage}</b></div></div><small class="source-line">Next: ${f.next}</small>`).join('')}</section></div><div class="grid cols" style="margin-top:14px"><section class="card"><div class="section-title"><h3>Priority projects</h3><button class="btn" onclick="go('Projects')">View all</button></div>${state.projects.map(p=>`<div class="project"><div class="row"><div><b>${p.name}</b><small class="muted">${p.size} · ${p.stage}</small></div><span class="badge">${p.truth}</span></div><div class="bar"><i style="width:${p.progress}%"></i></div></div>`).join('')}</section><section class="card founder-rule"><div class="section-title"><h3>Founder rule</h3></div><div>“If it doesn't increase contracted MW, financing probability, deployment velocity, or enterprise value — defer it.”</div></section></div>`}
function tasks(){const filtered=state.tasks.filter(t=>(state.taskFilter==='ALL'||t.tag===state.taskFilter||(state.taskFilter==='BLOCKED'&&t.blocked))&&t.name.toLowerCase().includes(state.taskSearch.toLowerCase()));return `<div class="toolbar"><input id="taskSearch" value="${state.taskSearch.replace(/"/g,'&quot;')}" placeholder="Search tasks…" oninput="setTaskSearch(this.value)"><button class="btn ${state.taskFilter==='ALL'?'selected':''}" onclick="setTaskFilter('ALL')">All</button><button class="btn ${state.taskFilter==='P0'?'selected':''}" onclick="setTaskFilter('P0')">P0</button><button class="btn ${state.taskFilter==='P1'?'selected':''}" onclick="setTaskFilter('P1')">P1</button><button class="btn ${state.taskFilter==='BLOCKED'?'selected':''}" onclick="setTaskFilter('BLOCKED')">Blocked</button></div><section class="card"><div class="section-title"><h3>Master tasks</h3><span class="badge">${filtered.length} shown · ${state.tasks.length} total</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Task</th><th>Priority</th><th>Impact</th><th>Status</th><th></th></tr></thead><tbody>${taskRows(filtered)}</tbody></table></div></section>`}
function projects(){const stages=['Prospect','Qualified','Site Survey','Technical Qualified','Proposal','LOI','PPA Negotiation','Executed PPA','Financing','Procurement','Construction','Commissioned','Operating'];return `<section class="card"><div class="section-title"><h3>Project lifecycle</h3><span class="badge">13 stages</span></div><div class="stage-grid">${stages.map((x,i)=>`<div class="stage"><span>${String(i+1).padStart(2,'0')}</span><b>${x}</b><small>${x==='LOI'?'1 project':x==='Prospect'?'TBD':'—'}</small></div>`).join('')}</div></section><section class="card" style="margin-top:14px"><div class="section-title"><h3>Known project records</h3><span class="badge">Evidence-first</span></div>${state.projects.map(p=>`<div class="project"><div class="row"><div><b>${p.name}</b><small>${p.size} · ${p.stage} · ${p.truth}</small></div><span class="badge">${p.ppr}</span></div><div class="project-grid"><span>Generation <b>${p.generation}</b></span><span>Term <b>${p.term}</b></span><span>CAPEX <b>${p.capex}</b></span></div></div>`).join('')}</section>`}
function pipeline(){return `<section class="card"><div class="section-title"><h3>Customer pipeline</h3><span class="badge">Evidence-first</span></div><div class="empty"><strong>No customer records synced into V1.</strong><br>Import the canonical Notion CRM before using this view for pipeline decisions.<br><br><button class="btn primary" onclick="alert('V2 integration boundary: Notion/CRM adapter')">Integration boundary</button></div></section>`}
function financing(){return `<div class="grid cols"><section class="card"><div class="section-title"><h3>Capital processes</h3></div>${state.finance.map(f=>`<div class="project"><div class="row"><b>${f.name}</b><span class="badge">${f.stage}</span></div><small>${f.next}</small><div class="source-line">Evidence: ${f.truth}</div></div>`).join('')}</section><section class="card"><div class="section-title"><h3>Bankability checklist</h3></div>${['Executed customer contract','Validated generation','Validated CAPEX','Structural compliance','Project financial model','Security / guarantee structure'].map((x,i)=>`<div class="task"><span class="dot ${i<2?'warn':''}"></span><div class="grow"><b>${x}</b><small>${i===0?'Priority: convert LOIs':i===1?'CGS validation required':'Verification required'}</small></div><span class="badge">${i<2?'OPEN':'PENDING'}</span></div>`).join('')}</section></div>`}
function portfolio(){return `<section class="card"><div class="section-title"><h3>Operating portfolio</h3><span class="badge">No fabricated metrics</span></div><div class="empty">No operating assets are currently represented as verified live portfolio data. The CGS record remains LOI-stage.</div></section>`}
function risks(){const risks=[['Contract conversion risk','HIGH','Convert top LOIs into executable PPAs'],['Financing / guarantee risk','HIGH','Confirm IDCOL/PFI security requirements'],['CAPEX assumption risk','HIGH','Establish one validated cost basis'],['Structural / wind-load risk','MEDIUM','Finalize BNBC/cyclone-zone engineering'],['Customer concentration risk','MEDIUM','Diversify beyond family-linked relationships']];return `<div class="grid cols"><section class="card"><div class="section-title"><h3>Active strategic risks</h3><span class="badge">5 tracked</span></div>${risks.map(r=>`<div class="risk"><div class="row"><b>${r[0]}</b><span class="badge">${r[1]}</span></div><p>Mitigation: ${r[2]}</p></div>`).join('')}</section><section class="card"><div class="section-title"><h3>Decision framework</h3></div>${['SCALE','EXPERIMENT','SHRINK','DEFER','KILL'].map(x=>`<div class="project decision"><b>${x}</b><small>Use when objective, constraints, evidence, expected value and downside are explicit.</small></div>`).join('')}</section></div>`}
function roadmap(){return `<div class="roadmap">${[['NOW','BANKABILITY',['CGS PPA execution','2 additional PPAs','Validated financial model','IDCOL / PFI pathway','GuarantCo submission']],['NEXT','DEPLOYMENT',['Financing close','Procurement','Construction','Commissioning','Monitoring + billing']],['LATER','SCALE',['Repeatable acquisition','Portfolio financing facility','NEOS automation','Storage / EV experiments','Distributed energy platform']]].map(p=>`<section class="card phase"><div class="phase-label">${p[0]}</div><h4>${p[1]}</h4><ul>${p[2].map((x,i)=>`<li><span class="check">${i===0&&p[0]==='NOW'?'●':'○'}</span>${x}</li>`).join('')}</ul></section>`).join('')}</div>`}
function documents(){return `<section class="card"><div class="section-title"><h3>Knowledge & documents</h3><span class="badge">Source-of-truth boundary</span></div><div class="grid doc-grid">${['Corporate','Commercial','Technical','Financial','Financing','Legal','Investor','Regulatory'].map(x=>`<div class="project doc"><b>${x}</b><small>Canonical records resolve to Notion / file storage. V1 does not pretend files are synced.</small></div>`).join('')}</div></section>`}
function content(){return state.screen==='CEO'?dashboard():state.screen==='Tasks'?tasks():state.screen==='Projects'?projects():state.screen==='Pipeline'?pipeline():state.screen==='Financing'?financing():state.screen==='Portfolio'?portfolio():state.screen==='Risks'?risks():state.screen==='Roadmap'?roadmap():documents()}
function render(){document.getElementById('root').innerHTML=`<div class="app">${sidebar()}<main class="main">${header()}<div class="screen active">${content()}</div></main><div class="mobile-nav">${nav.slice(0,5).map(([n,i])=>`<button class="${state.screen===n?'active':''}" onclick="go('${n}')">${icon(i)}<br>${n}</button>`).join('')}</div></div>`;if(window.lucide)lucide.createIcons()}
function go(n){state.screen=n;render()}
function setTaskFilter(f){state.taskFilter=f;render()}
function setTaskSearch(v){state.taskSearch=v;const rows=document.getElementById('taskRows');if(rows){const filtered=state.tasks.filter(t=>(state.taskFilter==='ALL'||t.tag===state.taskFilter||(state.taskFilter==='BLOCKED'&&t.blocked))&&t.name.toLowerCase().includes(v.toLowerCase()));rows.innerHTML=taskRows(filtered)}}
function newTask(){const name=prompt('New task name');if(!name)return;state.tasks.unshift({id:'T-'+String(state.tasks.length+1).padStart(3,'0'),name,meta:'Founder-created · Unassigned',tag:'P1',status:'Active',impact:'Medium',class:'EXPERIMENT',due:'TBD',blocked:false});state.screen='Tasks';render()}
render();