'use client';

import { FormEvent, useEffect, useState } from 'react';
import { supabaseBrowser } from '../lib/supabase';

type Task = { id:string; title:string; priority:string; status:string; workstream:string|null; due_date:string|null };
type Project = { id:string; name:string; stage:string; capacity_kw:number|null; evidence_level:string; next_gate:string|null; blocker:string|null };
type Finance = { id:string; provider_name:string; stage:string; next_action:string|null; evidence_level:string };

const nav=['Dashboard','Tasks','Projects','Financing','Risks & Decisions','Roadmap','Documents'];
const label=(s:string)=>s.replaceAll('_',' ');

export default function Home(){
  const [session,setSession]=useState<any>(null); const [screen,setScreen]=useState('Dashboard'); const [tasks,setTasks]=useState<Task[]>([]); const [projects,setProjects]=useState<Project[]>([]); const [finance,setFinance]=useState<Finance[]>([]); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
  const db=supabaseBrowser();
  async function load(){
    const {data:{session}}=await db.auth.getSession(); setSession(session); if(!session)return;
    const [{data:t},{data:p},{data:f}]=await Promise.all([db.from('tasks').select('id,title,priority,status,workstream,due_date').order('priority'),db.from('projects').select('id,name,stage,capacity_kw,evidence_level,next_gate,blocker').order('updated_at',{ascending:false}),db.from('financing_cases').select('id,provider_name,stage,next_action,evidence_level').order('updated_at',{ascending:false})]);
    setTasks(t||[]);setProjects(p||[]);setFinance(f||[]);
  }
  useEffect(()=>{load(); const {data}=db.auth.onAuthStateChange(()=>load()); return()=>data.subscription.unsubscribe()},[]);
  async function signIn(e:FormEvent){e.preventDefault();setError('');const {error}=await db.auth.signInWithPassword({email,password});if(error)setError(error.message)}
  async function addTask(){const title=window.prompt('Task name');if(!title)return;const {error}=await db.from('tasks').insert({title,priority:'P1',status:'TODO',impact:'Medium',strategic_action:'EXPERIMENT',evidence_level:'TBD'});if(error)window.alert(error.message);else load()}
  if(!session)return <main className="auth"><form className="card" onSubmit={signIn}><div className="eyebrow">NETSO OS</div><h1>CEO Command Center</h1><p className="muted">Operational system for bankability, contracts and deployment.</p><input aria-label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Founder email" required/><input aria-label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button className="primary">Sign in</button>{error&&<p>{error}</p>}</form></main>;
  const p0=tasks.filter(t=>t.priority==='P0'&&t.status!=='DONE'); const blocked=tasks.filter(t=>t.status==='BLOCKED');
  return <div className="shell"><aside className="sidebar"><div className="brand">NETSO OS <span className="muted">/ CEO</span></div><nav className="nav">{nav.map(n=><button className={screen===n?'active':''} key={n} onClick={()=>setScreen(n)}>{n}</button>)}</nav><button className="nav" onClick={()=>db.auth.signOut()}>Sign out</button></aside><main className="main"><div className="objective"><div><div className="eyebrow">90-day objective</div><h1>Make Netso financeable and deployable.</h1><div className="muted">Truth-first operating control. Unknown metrics remain TBD.</div></div>{screen==='Tasks'&&<button className="primary" style={{width:'auto',padding:'9px 14px'}} onClick={addTask}>+ New task</button>}</div>{screen==='Dashboard'&&<Dashboard tasks={tasks} projects={projects} finance={finance} p0={p0} blocked={blocked}/>} {screen==='Tasks'&&<Tasks tasks={tasks}/>} {screen==='Projects'&&<Projects projects={projects}/>} {screen==='Financing'&&<Financing finance={finance}/>} {['Risks & Decisions','Roadmap','Documents'].includes(screen)&&<div className="card"><div className="eyebrow">{screen}</div><h2>Operational module</h2><p className="muted">This module is staged for the persistent data layer. No unsupported records are displayed.</p></div>}</main></div>
}
function Dashboard({tasks,projects,finance,p0,blocked}:{tasks:Task[];projects:Project[];finance:Finance[];p0:Task[];blocked:Task[]}){return <><div className="grid kpis">{[['Executed PPAs','TBD'],['Contracted MW','TBD'],['Installed MW','TBD'],['Qualified Projects',String(projects.filter(p=>p.stage==='QUALIFIED').length)],['Financing Secured','TBD'],['Active Financing',String(finance.filter(f=>!['DISBURSED','REJECTED'].includes(f.stage)).length)],['Critical Blockers',String(blocked.length)],['Open Tasks',String(tasks.filter(t=>t.status!=='DONE').length)]].map(([l,v])=><div className="card kpi" key={l}><div className="label">{l}</div><div className="value">{v}</div></div>)}</div><section className="section card"><h2>Today — P0 / P1</h2><div className="rows">{p0.slice(0,5).map(t=><div className="row" key={t.id}><span>{t.title}</span><span className="pill">{t.priority} · {label(t.status)}</span></div>)}{!p0.length&&<div className="empty">No P0 tasks currently open.</div>}</div></section><section className="section card"><h2>Critical blockers</h2>{blocked.map(t=><div className="row" key={t.id}><span>{t.title}</span><span className="pill">BLOCKED</span></div>)}{!blocked.length&&<div className="empty">No blocked tasks.</div>}</section></>}
function Tasks({tasks}:{tasks:Task[]}){return <div className="card"><h2>Tasks</h2>{tasks.map(t=><div className="row" key={t.id}><span>{t.title}<small className="muted"> {t.workstream||''}</small></span><span className="pill">{t.priority} · {label(t.status)}</span></div>)}</div>}
function Projects({projects}:{projects:Project[]}){return <div className="card"><h2>Projects</h2>{projects.map(p=><div className="row" key={p.id}><span>{p.name} <small className="muted">{p.capacity_kw?`${p.capacity_kw} kWp`:''}</small></span><span className="pill">{label(p.stage)} · {p.evidence_level}</span></div>)}</div>}
function Financing({finance}:{finance:Finance[]}){return <div className="card"><h2>Financing</h2>{finance.map(f=><div className="row" key={f.id}><span>{f.provider_name}<small className="muted"> {f.next_action||''}</small></span><span className="pill">{label(f.stage)} · {f.evidence_level}</span></div>)}</div>}
